services:
  next_app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGPORT: ${DB_PORT}
    expose:
      - "${DB_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data

