version: '3.8'

services:
    next_app:
        image: {{ env.IMAGE_URL }}
        restart: always
        ports:
            - '{{ secrets.UD_PORT }}:{{ secrets.UD_PORT }}'
        environment:
            - PORT={{ secrets.UD_PORT }}
            - DB_HOST=db
            - DB_PORT={{ secrets.UD_DB_PORT }}
            - DB_USER={{ secrets.UD_DB_USER }}
            - DB_PASSWORD={{ secrets.UD_DB_PASSWORD }}
            - DB_DATABASE={{ secrets.UD_DB_DATABASE }}
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_USER={{ secrets.UD_DB_USER }}
            - POSTGRES_PASSWORD={{ secrets.UD_DB_PASSWORD }}
            - POSTGRES_DB={{ secrets.UD_DB_DATABASE }}
            - PGPORT={{ secrets.UD_DB_PORT }}
        expose:
            - '{{ secrets.UD_DB_PORT }}'
        volumes:
            - ./data/db:/var/lib/postgresql/data
