version: '3.8'

services:
    next_app:
        image: {{ env.IMAGE_URL }}
        restart: always
        ports:
            - '${PORT}:${PORT}'
        env_file: .env
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PGPORT: ${DB_PORT}
        expose:
            - '${DB_PORT}'
        volumes:
            - ./data/db:/var/lib/postgresql/data
