name: Push To Yandex Cloud CR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch .env
          echo PORT=${{ secrets.UD_PORT}} >> .env
          echo DB_HOST=${{ secrets.UD_DB_HOST }} >> .env
          echo DB_USER=${{ secrets.UD_DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.UD_DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.UD_DB_DATABASE }} >> .env

      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY }}
          CR_REPOSITORY: ${{ secrets.YC_CR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@b22db2965c8af6bf0980e8b026c5e80ad6e15adf
        env:
          IMAGE_URL: cr.yandex/crpk28lsfu91rns28316/yc-coi-github-action:${{ github.sha }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }} 
          vm-name: ${{ secrets.YC_VM_NAME }}
          vm-service-account-id: ${{ secrets.YC_VM_SERVICE_ACCOUNT_ID }} 
          vm-cores: 2
          vm-memory: 2 GB
          vm-core-fraction: 100
          vm-zone-id: ${{ secrets.YC_VM_ZONE_ID }}
          vm-subnet-id: ${{ secrets.YC_VM_SUBNET_ID }}
          vm-disk-type: network-hdd
          vm-disk-size: 16GB
          user-data-path: './user-data.yaml'
          docker-compose-path: './compose.yaml'
